[tool.poetry]
name = "tap-planetscaleapi"
version = "0.0.0"
description = "Singer tap for PlanetScaleAPI, built with the Meltano Singer SDK."
readme = "README.md"
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
    "ELT",
    "PlanetScaleAPI",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
license = "Apache-2.0"
urls.homepage = "https://github.com/edgarrmondragon/tap-planetscalepi"
urls.documentation = "https://github.com/edgarrmondragon/tap-planetscalepi#"
urls."Issue Tracker" = "https://github.com/edgarrmondragon/tap-planetscalepi/issues"
urls.repository = "https://github.com/edgarrmondragon/tap-planetscalepi"

[tool.poetry.dependencies]
python = ">=3.8"
importlib-resources = { version = "==6.4.*", python = "<3.9" }
fs-s3fs = { version = "~=1.1.1", optional = true }
singer-sdk = "~=0.41.0"
requests = "~=2.32.0"
toolz = "~=1.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "~=1.12.0"
pytest = ">=7.4.0"
requests-cache = ">=1.1.1,<1.3.0"
singer-sdk = { version = "~=0.41.0", extras = ["testing"] }
types-requests = "~=2.31.0.6"

[tool.poetry.extras]
s3 = ["fs-s3fs"]

[tool.mypy]
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "toolz.*",  # https://github.com/pytoolz/toolz/issues/496
]

[tool.ruff]
src = ["tap_planetscaleapi"]

[tool.ruff.lint]
ignore = [
    "ANN101",  # missing-type-self
    "ANN102",  # missing-type-cls
    "COM812",  # missing-trailing-comma
    "ISC001",  # single-line-implicit-string-concatenation
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
known-first-party = ["tap_planetscaleapi"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.scripts]
# CLI declaration
tap-planetscaleapi = 'tap_planetscaleapi.tap:TapPlanetScaleAPI.cli'

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "default:Fields in transformed catalog but not in records:UserWarning",
    "ignore:No records returned in stream:UserWarning",
    "ignore:No records were available to test:UserWarning",
]
xfail_strict = true
